Base: Parse Rumors
biqqles/flint pull request #12
Opened 2022-11-01 11:37 UTC by san-e

2022-11-01 19:14 UTC, biqqles requested changes
Thanks, this is a great feature! Some comments, might make some more later.

2022-11-01 19:14 UTC, biqqles commented on flint/entities/universe.py
> +            return {affiliation: list(dict.fromkeys(content)) for affiliation, content in rumors.items()}
Is `list(dict.fromkeys(content))` to remove dups? You could just return a set instead.

2022-11-01 19:14 UTC, biqqles commented on flint/entities/universe.py
> +                if type(npc.rumor) != list: npc.rumor = [npc.rumor]
Split to multiple lines

2022-11-01 19:14 UTC, biqqles commented on flint/entities/universe.py
> +        """All rumors offered on this base, of the form {faction -> rumors}"""
```suggestion
        """All rumors offered on this base, of the form {faction -> rumors}."""
```

2022-11-01 19:14 UTC, biqqles commented on flint/entities/universe.py
> +    def rumors(self, markup = "html") -> dict:
Only a valid type annotation in newer Python versions, we support back to 3.6

2022-11-01 19:14 UTC, biqqles commented on flint/entities/universe.py
> +            return {affiliation: list(dict.fromkeys(content)) for affiliation, content in rumors.items()}
Should probably have `Faction` objects as keys

2022-11-01 19:48 UTC, biqqles commented
I think my refactor should give equivalent output to yours, please let me know if I missed anything.

2022-11-04 14:04 UTC, san-e commented
Hi, thanks for the refactor! It produces identical output most of the time, but sometimes returns an empty `set()` object. Should be fixed by just adding a `if npc.rumor:` statement to the top of the npc loop

2022-11-16 17:46 UTC, merged

2022-11-16 17:46 UTC, biqqles commented
Thanks!